### ISSUE TITLE
Compatibility with styled-components major version 6

### ISSUE THREAD

**Issue by yichenchong** [winteragency/sanity-plugin-webhook#3]
I love using and working with this plugin so far, but I want to use a different Sanity plugin that requires styled-components major version 6, which this plugin doesn't seem compatible with. Are there any plans to make this compatible (or if it already is compatible, to update the dependencies) with future versions of styled-components, particularly v6?

**Comment by marcusforsberg** [comment]
Hey @yichenchong! Sorry for the long delay here, the notification for this issue must have been missed. 

I've pushed a new version, v1.1.0, which now supports/requires the very latest Sanity Studio, including styled-components v6.1. Let me know if you run into any further issues!
